name: Validate Sasi Branch Files

on:
  push:
    branches:
      - Sasi
  pull_request:
    branches:
      - Sasi

jobs:
  validate-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate file content
        run: |
          errors=0

          for file in $(find . -type f -name "*.txt"); do
            if ! grep -q "sasi" "$file"; then
              echo "Error: $file does not contain the word 'sasi'."
              errors=1
            else
              echo "Message: $file contains the word 'sasi'."
            fi
          done

          if [[ $errors -ne 0 ]]; then
            exit 1
          fi
